QualiSystems/cloudshell-cli

cloudshell/cli/service/cli_service.py
cloudshell/cli/session/connection_manager.py
cloudshell/cli/session/expect_session.py
cloudshell/cli/session/session_proxy.py
cloudshell/cli/session/ssh_session.py
cloudshell/configuration/cloudshell_cli_binding_keys.py
cloudshell/configuration/cloudshell_cli_bindings.py
cloudshell/configuration/cloudshell_cli_configuration.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/6)

Fixed context paths, added binding keys

---

cloudshell/cli/session/connection_manager.py
cloudshell/configuration/cloudshell_cli_configuration.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/8)

Added configuration fo pool size

---

cloudshell/cli/service/cli_service.py
cloudshell/cli/service/cli_service_interface.py
cloudshell/cli/session/connection_manager.py
cloudshell/cli/session/expect_session.py
cloudshell/cli/session/ssh_session.py
cloudshell/cli/session/telnet_session.py
cloudshell/configuration/cloudshell_cli_configuration.py
third_party_requirements.txt

Fixed telnet session, and ssh login error messages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/9)

7.0 refactoring

---

cloudshell/cli/session/connection_manager.py
cloudshell/cli/session/telnet_session.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/11)

Fixed telnet distruction and connection type

---

cloudshell/cli/command_template/command_template_service.py
cloudshell/cli/session/connection_manager.py
cloudshell/cli/session/expect_session.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/16)

Added expected map and error map to execute_command_map

---

cloudshell/cli/service/cli_service.py
cloudshell/configuration/cloudshell_cli_configuration.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/18)

some small fixes done on default config mode prompt

---

cloudshell/cli/service/cli_service.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/19)

another small fix in send command cli_service

---

cloudshell/cli/session/telnet_session.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/22)

Telnet issue

---

cloudshell/cli/command_template/command_template_service.py
cloudshell/cli/service/cli_service.py
cloudshell/cli/service/cli_service_interface.py
cloudshell/cli/session/expect_session.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/26)

Changed cli_service interfaces, added optional_args to method signatures

---

cloudshell/cli/session/expect_session.py
cloudshell/cli/session/ssh_session.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/28)

[BUGFIX #155043] ASA Shell - running restore running config on override with wrong non existing file still reload the switch

---

cloudshell/cli/command_template/command_template_service.py
cloudshell/cli/service/cli_service.py
cloudshell/cli/session/expect_session.py
cloudshell/cli/session/session_exceptions.py
requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/30)

Hardware expect changes

---

cloudshell/cli/session/expect_session.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/32)

added clean buffer timeout

---

cloudshell/cli/session/expect_session.py
cloudshell/cli/session/ssh_session.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/36)

small adjustment for CLI TCP Port

---

cloudshell/cli/helper/weak_key_dictionary_with_callback.py
cloudshell/cli/session/connection_manager.py
cloudshell/cli/session/connection_manager_exceptions.py
cloudshell/cli/session/session_validation_proxy.py
cloudshell/configuration/cloudshell_cli_bindings.py
cloudshell/configuration/cloudshell_cli_configuration.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/42)

[Bugfix 155334]: cloudshell-cli, call session destructor

---

cloudshell/cli/helper/singleton.py
cloudshell/cli/session/connection_manager.py
cloudshell/cli/session/console_session.py
cloudshell/cli/session/expect_session.py
cloudshell/cli/session/ssh_session.py
cloudshell/cli/session/tcp_session.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/44)

Adapt code using without inject

---

cloudshell/cli/command_template/command_template.py
cloudshell/cli/command_template/command_template_executor.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/49)

Refactoring session usage

---

cloudshell/cli/session/connection_params.py
cloudshell/cli/session/ssh_session.py
cloudshell/tests/cli/session/test_ssh_session.py
requirements.txt

Combined ericr_keyfile and ericr_scp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/54)

Ericr merge keyfile to scp

---

cloudshell/cli/session/connection_params.py
cloudshell/cli/session/ssh_session.py
cloudshell/tests/cli/session/test_ssh_session.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/52)

add RSA private key option to SSH login

---

cloudshell/cli/command_template/command_template_executor.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/55)

Add default value to action/error map in command executor

---

cloudshell/cli/command_mode_helper.py
cloudshell/cli/session/expect_session.py
cloudshell/cli/session/scpi_session.py
cloudshell/cli/session/session.py
cloudshell/cli/session/tl1_session.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/57)

add tl1 and scpi session types

---

cloudshell/cli/command_mode_helper.py
cloudshell/cli/session/expect_session.py
cloudshell/cli/session/session.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/56)

refactor with probe_for_prompt method

---

cloudshell/cli/session/expect_session.py
cloudshell/cli/session/session.py
cloudshell/cli/session_pool_context_manager.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/62)

Fixed bug reconnect on inactive sessions

---

cloudshell/cli/session/tcp_session.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/63)

Update to tcp session to allow ignoring a connection prompt

---

cloudshell/cli/command_mode.py
requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/65)

updated requirements and changed command mode

---

cloudshell/cli/cli_service_impl.py
cloudshell/cli/command_mode.py
cloudshell/cli/command_template/command_template.py
cloudshell/cli/command_template/command_template_executor.py
cloudshell/cli/session/expect_session.py
cloudshell/cli/session_pool_context_manager.py
tests/cli/session/test_expect_session.py

It'll be helpful to raise own exception from an error map
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/74)

raise an error from an error map

---

cloudshell/cli/configurator.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/82)

fixing overriding REGISTERED_SESSIONS

---

cloudshell/cli/session/telnet_session.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/84)

telnet session

---

.travis.yml
cloudshell/cli/service/cli_service.py
cloudshell/cli/service/node.py
cloudshell/cli/service/session_manager.py
cloudshell/cli/service/session_pool.py
cloudshell/cli/service/session_pool_manager.py
cloudshell/cli/session/connection_params.py
cloudshell/cli/session/expect_session.py
cloudshell/cli/session/session.py
cloudshell/cli/session/ssh_session.py
setup.py
test_requirements.txt
tests/cli/session/test_connection_params.py
tests/cli/session/test_expect_session.py
tests/cli/session/test_ssh_session.py
tests/cli/session/test_telnet_session.py
tests/cli/test_cli_service_impl.py
tests/cli/test_command_mode.py
tests/cli/test_command_mode_helper.py
tests/cli/test_node.py
tests/cli/test_session_manager.py
tests/cli/test_session_pool_context_manager.py
tests/cli/test_session_pool_manager.py
tox.ini

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/94)

python2 compatibilities

---

.gitattributes

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/96)

fix GH langs

---

.travis.yml
tox.ini

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/104)

add auto releases

---

cloudshell/cli/cli.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/108)

CLI deprecated import

---

cloudshell/cli/configurator.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-cli/115)

Take undefined session list from session dict
